package com.apex.command;
import android.app.*;import android.os.Bundle;import android.content.*;import android.graphics.*;import android.graphics.Typeface;import android.widget.*;import java.io.*;

public class ApexActivity extends Activity{
 private final int GOLD=Color.rgb(212,175,55); private TextView status,log,profile; private EditText mission;
 private static final String N="identity_name",P="identity_platform",A="identity_audience",T="identity_tone";
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());}
 private android.view.View ui(){
  ScrollView s=new ScrollView(this);s.setBackgroundColor(Color.rgb(7,9,13));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(22),dp(22),dp(22),dp(30));s.addView(r);
  r.addView(txt("APEX",32,GOLD,true));r.addView(txt("Independent • Brand-agnostic Mission Control",13,Color.LTGRAY,false));
  LinearLayout id=panel();id.addView(txt("ACTIVE IDENTITY",12,GOLD,true));profile=txt(label(),16,Color.WHITE,true);id.addView(profile);Button edit=btn("CONFIGURE CHANNEL IDENTITY");edit.setOnClickListener(v->editIdentity());id.addView(edit);r.addView(id);
  LinearLayout h=panel();h.addView(txt("MISSION",12,GOLD,true));mission=new EditText(this);mission.setHint("Describe a concrete objective…");mission.setTextColor(Color.WHITE);mission.setHintTextColor(Color.GRAY);mission.setMinLines(3);h.addView(mission);Button go=btn("CREATE VERIFIED BRIEF");go.setOnClickListener(v->execute());h.addView(go);r.addView(h);
  LinearLayout st=panel();st.addView(txt("STATUS",12,GOLD,true));status=txt("IDLE • Awaiting mission",16,Color.WHITE,true);st.addView(status);r.addView(st);
  LinearLayout ev=panel();ev.addView(txt("EVIDENCE",12,GOLD,true));log=txt("Completion requires a persisted artifact. No simulated success states.",12,Color.LTGRAY,false);ev.addView(log);Button share=btn("SHARE LATEST ARTIFACT");share.setOnClickListener(v->share());ev.addView(share);r.addView(ev);
  r.addView(txt("APEX • Missions • Identities • Evidence",11,Color.GRAY,false));return s;
 }
 private void editIdentity(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);EditText n=in("Identity / channel",pref(N,"Default"));EditText p=in("Platform",pref(P,"Unspecified"));EditText a=in("Audience",pref(A,"General"));EditText t=in("Tone",pref(T,"Clear and engaging"));b.addView(n);b.addView(p);b.addView(a);b.addView(t);new AlertDialog.Builder(this).setTitle("Channel identity").setView(b).setNegativeButton("CANCEL",null).setPositiveButton("SAVE",(d,w)->{getPreferences(0).edit().putString(N,val(n,"Default")).putString(P,val(p,"Unspecified")).putString(A,val(a,"General")).putString(T,val(t,"Clear and engaging")).apply();profile.setText(label());log.setText("Identity persisted: "+label());}).show();}
 private void execute(){String o=mission.getText().toString().trim();if(o.isEmpty()){status.setText("BLOCKED • Objective required");return;}status.setText("RUNNING • Creating artifact");new Thread(()->{try{String body=MissionPlanner.build(o,pref(N,"Default"),pref(P,"Unspecified"),pref(A,"General"),pref(T,"Clear and engaging"));File d=new File(getFilesDir(),"artifacts");if(!d.exists()&&!d.mkdirs())throw new IOException("artifact directory unavailable");File f=new File(d,"mission-"+System.currentTimeMillis()+".txt");try(FileOutputStream x=new FileOutputStream(f)){x.write(body.getBytes("UTF-8"));x.getFD().sync();}getPreferences(0).edit().putString("latest",f.getAbsolutePath()).apply();runOnUiThread(()->{status.setText("COMPLETED • Artifact persisted");log.setText("Verified: "+f.getName()+" • "+f.length()+" bytes");});}catch(Exception e){runOnUiThread(()->{status.setText("FAILED • No completion recorded");log.setText("Failure: "+e.getMessage());});}}).start();}
 private void share(){File f=new File(pref("latest",""));if(!f.isFile()){log.setText("No verified artifact available.");return;}try{BufferedReader br=new BufferedReader(new FileReader(f));StringBuilder b=new StringBuilder();String x;while((x=br.readLine())!=null)b.append(x).append('\n');br.close();Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_SUBJECT,"APEX Mission Artifact");i.putExtra(Intent.EXTRA_TEXT,b.toString());startActivity(Intent.createChooser(i,"Share APEX artifact"));}catch(Exception e){log.setText("Share failed: "+e.getMessage());}}
 private String label(){return pref(N,"Default")+" • "+pref(P,"Unspecified");}private String pref(String k,String d){return getPreferences(0).getString(k,d);}private String val(EditText e,String d){String s=e.getText().toString().trim();return s.isEmpty()?d:s;}private EditText in(String h,String v){EditText e=new EditText(this);e.setHint(h);e.setText(v);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.GRAY);return e;}
 private LinearLayout panel(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(18),dp(16),dp(18),dp(16));l.setBackgroundColor(Color.rgb(24,24,24));return l;}private TextView txt(String x,int z,int c,boolean b){TextView t=new TextView(this);t.setText(x);t.setTextSize(z);t.setTextColor(c);t.setPadding(0,dp(7),0,dp(7));if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private Button btn(String x){Button b=new Button(this);b.setText(x);b.setTextColor(Color.BLACK);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackgroundColor(GOLD);return b;}private int dp(int x){return(int)(x*getResources().getDisplayMetrics().density);}
}